global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'kavenegar_application'
    # Assuming your .NET application exposes metrics on port 5000 and the /metrics endpoint.
    static_configs:
      - targets: ['host.docker.internal:5000']